USE [master]
GO

/****** Object:  Database [Purity_PowerBI_data]    Script Date: 04/11/2017 14:39:00 ******/
CREATE DATABASE [Purity_PowerBI_data] ON  PRIMARY 
( NAME = N'Purity_PowerBI', FILENAME = N'F:\SrvApps\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Purity_PowerBI.mdf' , SIZE = 2158592KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Purity_PowerBI_log', FILENAME = N'E:\SrvApps\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\Purity_PowerBI_log.ldf' , SIZE = 2160960KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Purity_PowerBI_data] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Purity_PowerBI_data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Purity_PowerBI_data] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET ARITHABORT OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Purity_PowerBI_data] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Purity_PowerBI_data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Purity_PowerBI_data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Purity_PowerBI_data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Purity_PowerBI_data] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Purity_PowerBI_data] SET  READ_WRITE 
GO

ALTER DATABASE [Purity_PowerBI_data] SET RECOVERY FULL 
GO

ALTER DATABASE [Purity_PowerBI_data] SET  MULTI_USER 
GO

ALTER DATABASE [Purity_PowerBI_data] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Purity_PowerBI_data] SET DB_CHAINING OFF 
GO


